### ISSUE TITLE
模型路径识别不出来

### ISSUE THREAD

**Issue by zer0s0** [SupRL/WorldModelTrainer#3]
请问为什么我的模型路径测试时一直报错？以下是我的部分代码，我把模型.pth放在了commit文件里面试了两次还是报错，是对路径写法有什么要求吗？
#第一次 world_model_path = r"./world_model_1023.0_00049k.pth" # note: 这里需要引入相对路径
#第二次 world_model_path = r"./commit/world_model_1023.0_00049k.pth" # note: 这里需要引入相对路径
ckpt = torch.load(world_model_path)
model.load_state_dict(ckpt['model_state'])
![微信图片编辑_20230817102015](https://github.com/SupRL/WorldModelTrainer/assets/106174214/7313805d-5222-405d-8c59-da06032a1aca)

**Comment by zer0s0** [comment]
还有报错能不能不算提交次数，这样搞的debug很麻烦

**Comment by SupRL** [comment]
选手您好，在导入模型路径时需要引入相对路径，例如: `world_model_path=str(Path(__file__).parent.absolute() / 'world_model_1023.0_00049k.pth')`,可以看一下仓库中的predcit.py中的示例
![image](https://github.com/SupRL/WorldModelTrainer/assets/141795272/717c11e7-9615-4605-9a23-ed355e9e5df6)

**Comment by SupRL** [comment]
选手您好，在导入模型路径时需要引入相对路径，例如:
 `world_model_path=str(Path(__file__).parent.absolute() / 'world_model_1023.0_00049k.pth')`;
在src/predict.py 中有导入模型的示范
![image](https://github.com/SupRL/WorldModelTrainer/assets/141795272/3ba12fbe-d1d8-4916-8988-5311950675ec)

**Comment by SupRL** [comment]
> 
您好，这个建议我们会考虑一下的，近期会有一个更新。

**Comment by SupRL** [comment]
> 还有报错能不能不算提交次数，这样搞的debug很麻烦

您好，这个建议我们会考虑一下的，近期会有一个更新。
